// <auto-generated />
using System;
using CasCap;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasCap.Migrations
{
    [DbContext(typeof(AgentRuntimeDbContext))]
    [Migration("20261006043028_InitialAgentDefinitions")]
    partial class InitialAgentDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasCap.Entities.ActiveAgentDefinitionEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("agent_name");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TenantId", "AgentName")
                        .HasName("pk_active_agent_definitions");

                    b.HasIndex("TenantId", "AgentName", "SnapshotId")
                        .HasDatabaseName("ix_active_agent_definitions_tenant_agent_snapshot");

                    b.ToTable("active_agent_definitions", "agent_runtime");
                });

            modelBuilder.Entity("CasCap.Entities.AgentDefinitionSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("agent_name");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("change_reason");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("definition_version");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("published_by");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_definition_snapshots");

                    b.HasAlternateKey("TenantId", "AgentName", "Id")
                        .HasName("ak_agent_definition_snapshots_tenant_agent_id");

                    b.HasIndex("TenantId", "AgentName", "DefinitionVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_definition_snapshots_tenant_agent_version");

                    b.HasIndex("TenantId", "AgentName", "PublishedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_agent_definition_snapshots_tenant_agent_published");

                    b.ToTable("agent_definition_snapshots", "agent_runtime");
                });

            modelBuilder.Entity("CasCap.Entities.ActiveAgentDefinitionEntity", b =>
                {
                    b.HasOne("CasCap.Entities.AgentDefinitionSnapshotEntity", "Snapshot")
                        .WithMany()
                        .HasForeignKey("TenantId", "AgentName", "SnapshotId")
                        .HasPrincipalKey("TenantId", "AgentName", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_active_agent_definitions_snapshot");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
